/** @file
 * General info about digits.
 *
 * @author Cley Faye
 * Licensing informations in LICENSE.md file.
 */

// GSize
// ResourceId
#include <pebble.h>
// Associated header
#include "digit_info.h"

// ===================
// PRIVATE VARIABLES =
// ===================

/** Segment resource identifiers for big digits */
const ResourceId big_segment_res_ids[SEGMENTS_ORIENTATION_COUNT] = {
    RESOURCE_ID_BIGDIGIT_VERTICAL_WHITE,
    RESOURCE_ID_SEGMENT_BIG_0_WHITE,
    RESOURCE_ID_SEGMENT_BIG_1_WHITE,
    RESOURCE_ID_SEGMENT_BIG_2_WHITE,
    RESOURCE_ID_SEGMENT_BIG_3_WHITE,
    RESOURCE_ID_SEGMENT_BIG_4_WHITE,
    RESOURCE_ID_SEGMENT_BIG_5_WHITE,
    RESOURCE_ID_SEGMENT_BIG_6_WHITE,
    RESOURCE_ID_SEGMENT_BIG_7_WHITE,
    RESOURCE_ID_SEGMENT_BIG_8_WHITE,
    RESOURCE_ID_BIGDIGIT_HORIZONTAL_WHITE,
    RESOURCE_ID_SEGMENT_BIG_9_WHITE,
    RESOURCE_ID_SEGMENT_BIG_10_WHITE,
    RESOURCE_ID_SEGMENT_BIG_11_WHITE,
    RESOURCE_ID_SEGMENT_BIG_12_WHITE,
    RESOURCE_ID_SEGMENT_BIG_13_WHITE,
    RESOURCE_ID_SEGMENT_BIG_14_WHITE,
    RESOURCE_ID_SEGMENT_BIG_15_WHITE,
    RESOURCE_ID_SEGMENT_BIG_16_WHITE,
    RESOURCE_ID_SEGMENT_BIG_17_WHITE
};

/** Segment resource identifiers for medium digits */
const ResourceId medium_segment_res_ids[SEGMENTS_ORIENTATION_COUNT] = {
    RESOURCE_ID_MEDIUMDIGIT_VERTICAL_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_0_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_1_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_2_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_3_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_4_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_5_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_6_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_7_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_8_WHITE,
    RESOURCE_ID_MEDIUMDIGIT_HORIZONTAL_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_9_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_10_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_11_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_12_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_13_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_14_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_15_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_16_WHITE,
    RESOURCE_ID_SEGMENT_MEDIUM_17_WHITE
};

// ==================
// PUBLIC VARIABLES =
// ==================

const GSize digit_dimensions[DIGITS_SIZE_COUNT] = {
    { .w = 46, .h = 83 },
    { .w = 42, .h = 77 }
};

const ResourceId* const segment_res_ids[DIGITS_SIZE_COUNT] = {
    big_segment_res_ids,
    medium_segment_res_ids
};

